import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  ["tutorial-sidebar"]: [{ type: "autogenerated", dirName: "tutorial" }],
  ["hytale-unified-ui-sidebar"]: [
    { type: "autogenerated", dirName: "hytale-unified-ui" },
  ],
};

export default sidebars;
